### ISSUE TITLE
How did you all generate this?

### ISSUE THREAD

**Issue by alita-moore** [octokit/types.ts#287]
would love to do this for my company's backend. Was it auto-generated?

**Comment by gr2m** [comment]
Hi Alita! I shared some background story about how we generate the types and endpoint methods in this blog post: https://github.blog/2020-04-09-from-48k-lines-of-code-to-10-the-story-of-githubs-javascript-sdk/

It evolved a bit since the post. 

1. The source of truth is GitHub's official OpenAPI spec at https://github.com/github/rest-api-description/. 
2. We pull the OpenAPI specs into https://github.com/octokit/openapi using a daily cron job. In that repository we amend the official spec with information we need for deprecations, in case of parameter name changes or operationID changes, which we use to derive the method names from in https://github.com/octokit/plugin-rest-endpoint-methods.js/.
3. For each new release of octokit/openapi, a new pull request is created in https://github.com/octokit/openapi-types.ts, which is a 1:1 transpilation from the OpenAPI spec to TypeScript using https://github.com/drwpow/openapi-typescript
4. For each new release of octokit/openapi-types, a new pull request is created here in this pull request, where [`src/generated/Endpoints.ts`](https://github.com/octokit/types.ts/blob/d8dbee8d1767f16b81fa8d2a10ab86669007653d/src/generated/Endpoints.ts) gets updated. And we also keep track of the bug fixes and features that `octokit/types` inherits from `octokit/openapi-types`, as its using it internally. 
5. New releases for both `octokit/types` and `octokit/openapi` create new pull requests in https://github.com/octokit/plugin-rest-endpoint-methods.js/ and other repositories, wherever we need the OpenAPI spec or use the `Endpoints` from `octokit/types`

Other automation details:

- Our releases are full automated using https://github.com/semantic-release/semantic-release (e.g. see [release.yml](https://github.com/octokit/types.ts/blob/master/.github/workflows/release.yml))
- The cross repository notification about releases is done using https://github.com/apps/octokit-release-notifier/ & https://github.com/gr2m/release-notifier-action/
- The relevant repository act on the `repository_dispatch` events created by https://github.com/apps/octokit-release-notifier/ and create the pull requests, which I review, adapt the commit message for the release automation, then these PRs trigger a new release, which in turn create pull requests in other repositories, until it trickled all through :)

Let me know if you have any further questions
