### ISSUE TITLE
Type 'number' is not assignable to type '200'

### ISSUE THREAD

**Issue by austenstone** [octokit/types.ts#392]
I'm getting type errors for response type. Why?

```typescript
const response: Endpoints['GET /orgs/{org}']['response'] = await octokit.request(`GET /orgs/${input.org}`);
```

```
Type 'OctokitResponse<any, number>' is not assignable to type 'OctokitResponse<{ login: string; id: number; node_id: string; url: string; repos_url: string; events_url: string; hooks_url: string; issues_url: string; members_url: string; public_members_url: string; avatar_url: string; ... 34 more ...; updated_at: string; }, 200>'.
  Type 'number' is not assignable to type '200'.ts(2322)
```

package.json
```json
  "dependencies": {
    "@actions/core": "^1.8.2",
    "@actions/github": "^5.0.3",
    "@octokit/types": "^6.34.0"
  },
```

**Comment by levenleven** [comment]
Typescript can't identified which route is called because of dynamic value of `GET /orgs/${input.org}` so it fallbacks to `string`.

If you'll call it as `await octokit.request('GET /orgs/{org}', { org: input.org });` as in example in [docs](https://docs.github.com/en/rest/orgs/orgs#get-an-organization) - it will be able to resolve the response type properly (also explicit typing for response won't be required)
