### ISSUE TITLE
[BUG]: rest.issues.listForRepo, types of property state are incompatible

### ISSUE THREAD

**Issue by till** [octokit/types.ts#549]
### What happened?

I am using vanialla JavaScript and octokit (rest) to find tickets in a GitHub repository. For the following code, vscode gives me an error message/warning, claiming that `state: 'open'` of is not compatible: 

```
		// look for an open issue for the component
		const parameters = {
			owner: this.owner,
			repo: this.repository,
			labels: labels.join(','),
			state: 'open',
			headers: requestHeaders,
		}

		return this.kit.rest.issues.listForRepo(parameters).then((response) => {
```

![octokit error](https://github.com/octokit/types.ts/assets/27003/b928ab6e-f363-4a8e-a4ec-76233518dd71)

### Versions

    "@octokit/core": "^4.2.1",
    "@octokit/rest": "^19.0.11"

### Relevant log output

```shell
See screenshot above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
I can't reproduce this issue.

Can you check to see if the latest version works? If not, are you able to check which version broke the intelisense in VS code?

Sometimes this happens because the TS intellisense gets stuck, and you need to restart it.
If you press <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and then select Restart Extension Host

**Comment by wolfy1339** [comment]
@till Can you still reproduce this issue?

**Comment by till** [comment]
No, stopped using this. I feel like I provided everything I could. 🤷🏻‍♂️
