### ISSUE TITLE
Distributing typescript files breaks pkg bundling

### ISSUE THREAD

**Issue by hipstersmoothie** [octokit/types.ts#72]
**What happened?**

In Octokit v16 we were able to successfully use `pkg` by zeit to create binaries of  https://github.com/intuit/auto/.

After the v17 upgrade we started getting this error while trying to run pkg.

![Screen Shot 2020-05-18 at 10 51 27 AM](https://user-images.githubusercontent.com/1192452/82244211-be93fb00-98f5-11ea-8fe0-601a6ea43a1e.png)

**What did you expect to happen?**

Pkg runs without complaining about uncompiled typescript files

**What the problem might be**

I'm pretty sure this is because this package publishes uncompiled typescript. I think pkg works by walking through the `main` of each included module and does it's magic.

I think this package should follow the same structure as a definitely typed package.

- distribute only .d.ts files
-  "main": "",
-  "types": "dist/index.d.ts",

**Comment by gr2m** [comment]
I use [`@pika/pack`](https://github.com/pikapkg/pack) for bundling before publishing. You can see the contents of the published package at https://unpkg.com/browse/@octokit/types@4.0.1/

I think that not all `@octokit/*` packages have been updated to the latest `@octokit/types` though, so you might see different versions in your dependency tree. Check with `npm ls @octokit/types`. This is due to Greenkeeper phasing out. I'll transition to Dependabot but didn't get to it yet.

**Comment by hipstersmoothie** [comment]
Ah yes you're right. I edited my lock file to align the version of `@octokit/types` to `2.16.2` and everything works. Sorry for the noise!
